### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by jeehmilena** [EpicentroTec/epicentro#1]
Logo do Epicentro Tecnologia

**Comment by jeehmilena** [comment]
@josealbertorodriguesjunior  @linsgabriel  @aa779  

![logo-epicentro-8](https://cloud.githubusercontent.com/assets/8833388/8555676/e5d30f14-24c7-11e5-81ba-5d26ad68cc54.png)

**Comment by juniorlimajj** [comment]
Já pode fechar esta Issue!!!

**Comment by aa779** [comment]
![logonov2](https://cloud.githubusercontent.com/assets/8723379/8891372/21a23784-32fd-11e5-8b16-8ad44d1cc83e.jpg)
![logonov2](https://cloud.githubusercontent.com/assets/8723379/8891373/21a6437e-32fd-11e5-833d-437ebd6bae90.png)

**Comment by aa779** [comment]
![logonov2](https://cloud.githubusercontent.com/assets/8723379/8891378/571579bc-32fd-11e5-9110-0ef01f82fdec.png)
