### ISSUE TITLE
Conteúdo - Módulo Frase

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#10]
Criação da frase do `(minibloco)`;
Imagem de fundo (anexar no [drive](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg) e mandar link aqui);
Conforme design #9.

**Comment by joaosaragossa** [comment]
"A Epicentro conta com profissionais especializados e sintonizados com as tendencias do mercado de desenvolvimento web"

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final:
- Quero ver uma foto de fundo que ocupe 100% da tela
- Quero o conteúdo centralizado em 1000px de largura
- Quero ver uma faixa branca com 100% de largura e 280px de altura;
- Quero ver uma frase centralizada na horizontal e vertical com a cor #520034 e a fonte #9
