### ISSUE TITLE
Conteúdo - Ícones do Módulo Portifólio

### ISSUE THREAD

**Issue by joaosaragossa** [EpicentroTec/epicentro#100]
Precisamos reunir os logos dos projetos que irão estar no módulo Portfolio:
- [x] Descubra Ubatuba
- [x] Recanto Domus
- [x] Avante
- [x] Pizzaria

@linsgabriel @aa779 @jeehmilena Favor fazer upload dos respectivos logos [nesta pasta](https://drive.google.com/folderview?id=0B0luQkerNSInfktjT2doSkNkakttRWpNd2pRMjE0QU9jTnVEZ3BYaXFuQVJYdmxmRXRITVE&usp=sharing_eid&tid=0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg).

**Comment by linsgabriel** [comment]
@aa779 e eu 
Temos que enviar os screenshots e miniaturas para esta pasta! 
Temos até amanhã!
