### ISSUE TITLE
Pagina Temporaria

### ISSUE THREAD

**Issue by jeehmilena** [EpicentroTec/epicentro#106]
# CRITÉRIOS DE ACEITAÇÃO

Eu sendo usuário final, 
- Quero ver uma imagem de fundo ocupando 100% da tela
- Quero ver uma faixa branca no centro da foto
- Quero ver o logo centralizado na horizontal e na vertical da faixa
  -Quero ver a frase "Estamos chegando...Em breve nosso site no ar!", centralizado na horizontal e vertical, com a fonte #9 e cor #9

**Comment by jeehmilena** [comment]
**Pagina final**

![pagina-temporaria](https://cloud.githubusercontent.com/assets/8833388/9253169/cc6b57d6-41b2-11e5-9833-66f0b167225c.jpg)

**Imagem do fundo**
![jumbotron1](https://cloud.githubusercontent.com/assets/8833388/9253188/ea1d5fea-41b2-11e5-844c-b8ed1daf03bf.jpg)

**Comment by linsgabriel** [comment]
Amanhã (sexta 14/08) faço isso e colocamos no ar!

**Comment by aa779** [comment]
Concluído e publicado. Arquivos no repositório site-provisório.

Acessem: http://epicentro.net.br

@linsgabriel @jeehmilena @joaosaragossa @josealbertorodriguesjunior

**Comment by jeehmilena** [comment]
@linsgabriel  e @aa779  o site quebrou na minha resolução, vai ter que ter uma correção 

![sem titulo](https://cloud.githubusercontent.com/assets/8833388/9288929/33b7f722-4335-11e5-8146-be2636df5f7c.jpg)

**Comment by linsgabriel** [comment]
@aa779 
Irão haver mais correções?
