### ISSUE TITLE
Frases Modulo Jumboton

### ISSUE THREAD

**Issue by jeehmilena** [EpicentroTec/epicentro#112]
Criação de mais 2 frases para fazer parte do slider que vai ter no modulo jumbotron

**Comment by linsgabriel** [comment]
Já temos todas as frases?
@EpicentroTec/owners

**Comment by joaosaragossa** [comment]
@linsgabriel Sim, estão no HTML desse módulo

**Comment by linsgabriel** [comment]
Issue fechada!
