### ISSUE TITLE
Otimização de imagens

### ISSUE THREAD

**Issue by aa779** [EpicentroTec/epicentro#119]
@jeehmilena , precisa passar todas imagens pelo "Salvar para Web" para diminuir os arquivos sem perder muito a qualidade. Use qualidade média na maioria dos arquivos e baixa em casos específicos de imagens sem muitos contrastes.

Imagens que ficarão com 100% da largura da tela deixar com 1920px de largura.

As imagens enviadas nos meus últimos PRs (Portfólio, logos e screenshots; e Jumbotron, jumbotron3.jpg) já estão otimizadas. NÃO SALVE novamente para não perder mais qualidade.

**Comment by linsgabriel** [comment]
@aa779 
@jeehmilena 
Podemos fechar essa issue??

**Comment by aa779** [comment]
Reabrindo esta issue para realização da tarefa. Vou definir quais resoluções e se compensa ter versões diferentes de cada arquivo de imagem. Isto pode influenciar no CSS responsivo do módulo.

**Comment by jeehmilena** [comment]
Olha eu já fiz essa tarefa ok??
