### ISSUE TITLE
Conteúdo - Módulo Menu

### ISSUE THREAD

**Issue by jeehmilena** [EpicentroTec/epicentro#13]
Critérios de aceitação para o modulo menu, e conteúdos, descrição e etc 
 @EpicentroTec/owners

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final:
- Quero ver um retângulo com 918 x 85 de cor branca, centralizado no topo;
- Quero ver o logo alinhado a esquerda;
- Quero ver os itens "SERVIÇOS, PORTIFÓLIO, EQUIPE, CONTATOS", alinhados a direita com a fonte #9 e cor #842c2e

**Comment by joaosaragossa** [comment]
Que fonte, @jeehmilena ?
