### ISSUE TITLE
Revisão

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#134]
- Módulo Frase -> espaçamentos verticais
- Módulo Portfólio -> espaçamentos verticais
- Módulo Portfólio -> setas para resoluções a partir de 1300px;
- Módulo Jumbotron -> Pode melhorar  a visualização do texto, talvez posicionamento ou tamanho mesmo.

**Comment by linsgabriel** [comment]
@joaosaragossa  
Atribui pra vc, mas se não der pra fazer hoje, terminamos amanhã!
Valeu.

**Comment by joaosaragossa** [comment]
@linsgabriel Por mim, podemos fechar
