### ISSUE TITLE
Revisão

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#136]
Após fazer alguns testes cheguei a conclusão que deve ser feita uma revisão geral, principalmente do visual. 
@EpicentroTec/owners

**Comment by jeehmilena** [comment]
Em qual parte no visual? @linsgabriel

**Comment by jeehmilena** [comment]
@EpicentroTec/owners 

# Ajustes para a revisão

**1920**
- Ta sem o menu
- Modulo serviços está com espaço sobrando em baixo e está bem próximo do título, e alguns textos estão saindo das áreas dos post its 
- Modulo portfólio está com as setas muito afastadas
- Modulo equipe também está com um espaço sobrando em baixo
- Modulo contato também esta com um espaço sobrando em baixo
- Footer esta faltando um espaçamento nas entrelinhas entre o titulo telefone e o numero do telefone

**1024**
- Ta sem o menu
- Modulo serviços alinhar os post its
- Modulo equipe também está com um espaço sobrando em baixo
- Modulo contato também esta com um espaço sobrando em baixo
-  Footer esta faltando um espaçamento nas entrelinhas entre o titulo telefone e o numero do telefone

**700**
- Menu não esta alinhado conforme o logo
- Modulo serviços alinhar os post its
- Modulo equipe também está com um espaço sobrando em baixo
- Modulo contato também esta com um espaço sobrando em baixo
-  Footer esta faltando um espaçamento nas entrelinhas entre o titulo telefone e o numero do telefone

**320**
- Menu não esta alinhado conforme o logo
- Modulo portfólio está responsivo??? (pra mim não está)
- Modulo contato também esta com um espaço sobrando em baixo
  -Footer alinhar redes sociais

**Comment by aa779** [comment]
Trocar as palavras "posticks" por "post its"! :D

**Comment by aa779** [comment]
As resoluções são estas mesmo? Sugiro, no mínimo, que 700 passe para 800px. Mas, se for o caso, fazer também uma intermediária entre 1024 e 1440 (a faixa mais utilizada) e outra acima de 1440, que compreende os 1920.

**Comment by joaosaragossa** [comment]
@jeehmilena Preciso que você me esclareça alguns pontos:

## 1920
1. No caso do módulo serviços, o que exatamente está bem próximo do título e qual seria a margem de distancia correta?

## 1024, 700, 320
1. O que significa alinhar os posticks?

**Comment by aa779** [comment]
O módulo frase já esteve certo em algum momento, com a foto preenchendo toda tela sem a frase, antes de aparecer equipe. Agora, o módulo equipe voltou a aparecer antes da hora. @jeehmilena, dá uma olhada nisso, por favor!? Já conversamos algumas vezes sobre isto.

**Comment by aa779** [comment]
Verificando agora com o master atualizado, realmente, a segunda resolução é 800 e não 700px.

**Comment by jeehmilena** [comment]
![screenshot-localhost 2015-08-24 10-12-04](https://cloud.githubusercontent.com/assets/8833388/9444625/3e8d2a98-4a5e-11e5-9708-2ca3311ce09d.png)
![screenshot-localhost 2015-08-24 10-12-57](https://cloud.githubusercontent.com/assets/8833388/9444626/3e93234e-4a5e-11e5-85c6-53a9cb0b6a38.png)
![screenshot-localhost 2015-08-24 10-15-11](https://cloud.githubusercontent.com/assets/8833388/9444627/3e982f2e-4a5e-11e5-937f-95fb1460c090.png)
![screenshot-localhost 2015-08-24 10-16-06](https://cloud.githubusercontent.com/assets/8833388/9444628/3e9f173a-4a5e-11e5-9cf1-4c4b01e7331f.png)
![screenshot-localhost 2015-08-24 10-20-34](https://cloud.githubusercontent.com/assets/8833388/9444630/3ea5672a-4a5e-11e5-9559-ab56289c3b48.png)
![screenshot-localhost 2015-08-24 10-22-36](https://cloud.githubusercontent.com/assets/8833388/9444629/3ea586e2-4a5e-11e5-8f44-71e4541b3203.png)
![screenshot-localhost 2015-08-24 10-24-12](https://cloud.githubusercontent.com/assets/8833388/9444631/3eb7d9be-4a5e-11e5-8722-fa2722698ce4.png)
![screenshot-localhost 2015-08-24 10-25-04](https://cloud.githubusercontent.com/assets/8833388/9444632/3ebe2fda-4a5e-11e5-943c-5cb779a09d1e.png)
![screenshot-localhost 2015-08-24 10-26-44](https://cloud.githubusercontent.com/assets/8833388/9444633/3ec318a6-4a5e-11e5-8efc-39ee3cd015a0.png)
![screenshot-localhost 2015-08-24 10-30-35](https://cloud.githubusercontent.com/assets/8833388/9444634/3ec9b9fe-4a5e-11e5-8ccd-50719f21cdff.png)
![screenshot-localhost 2015-08-24 10-48-55](https://cloud.githubusercontent.com/assets/8833388/9444635/3ed0a476-4a5e-11e5-9eae-0b355ee27155.png)
![screenshot-localhost 2015-08-24 10-50-14](https://cloud.githubusercontent.com/assets/8833388/9444637/3ed6a060-4a5e-11e5-9d1c-7e3baa5dc3f1.png)
![screenshot-localhost 2015-08-24 10-51-49](https://cloud.githubusercontent.com/assets/8833388/9444638/3ee4258c-4a5e-11e5-8f6d-4e58d66112d5.png)
![screenshot-localhost 2015-08-24 10-54-03](https://cloud.githubusercontent.com/assets/8833388/9444639/3ee892ca-4a5e-11e5-8fb9-8bcb4e109ba0.png)
@aa779 e @joaosaragossa 
Bom acho que ta bem explicado agora

**Comment by joaosaragossa** [comment]
@jeehmilena Na resolução 1025 o módulo serviços fica assim:

![servicos](https://cloud.githubusercontent.com/assets/6151234/9444950/f07c2bea-4a5f-11e5-87f8-2d804dec34e7.png)

A minha ideia inicial era trabalhar com medidas responsivas pra manter sempre 5 postits lado a lado em resoluções maiores de 1024, mas como foi decidido usar medidas fixas existe essa quebra.

**Comment by jeehmilena** [comment]
Deixa assim mesmo não vou ficar esquentando a cabeça com esse módulo além do que depois de lançado ele vai ser refeito

**Comment by joaosaragossa** [comment]
@jeehmilena Quando você diz alinhar seria isso?

![screencapture-localhost-projects-epicentro-1440433830174](https://cloud.githubusercontent.com/assets/6151234/9445826/87c00b94-4a64-11e5-8434-b92206a73acc.png)

**Comment by linsgabriel** [comment]
- Portfólio está responsivo :) 
- Diminui o espaço das setas (possível ver somente nessa resolução ai `1960px`);
- Menu está e sempre esteve alinhado. Não sei o que acontece no seu @jeehmilena. Temos que ver isso depois.

**Comment by linsgabriel** [comment]
![Uploading screenshot-localhost 2015-08-24 13-40-02.png…]()

**Comment by linsgabriel** [comment]
![Uploading screenshot-localhost 2015-08-24 13-40-02.png…](print)

**Comment by joaosaragossa** [comment]
@linsgabriel o texto abaixo do laptop do módulo portfólio está assim aqui:
![captura de tela de 2015-08-24 18 54 27](https://cloud.githubusercontent.com/assets/6151234/9453576/b1d8ea04-4a91-11e5-8332-8f84cb94e052.png)

**Comment by jeehmilena** [comment]
@EpicentroTec/owners  o modulo frase desapareceu : /

**Comment by linsgabriel** [comment]
Q loucura!

**Comment by linsgabriel** [comment]
@joaosaragossa assume o/

**Comment by joaosaragossa** [comment]
Finished!

**Comment by aa779** [comment]
Mais alguns PEQUENOS ajustes visuais:
- O logo do topo ainda está fora de proporção. Para verificar, teste a resolução abaixo de 600px, onde está apenas o "asterisco" e perceba a diferença. Pode-se também comparar com o logo do rodapé, rolando a página até o final, mantendo os dois em tela.
- Ajustar os percevejos 1px para baixo e 1px para direita para esconder aquela faixinha branca embaixo deles,
- O hambúrguer ainda não está alinhado em relação ao logo nas resoluções abaixo de 600px. 
- As três faixas devem ser menores e ligeiramente arredondadas (talvez trocar o uso de caracter da fonte de símbolos por CSS ou um PNG), mais parecidas com o que está no design:
  ![mobile](https://cloud.githubusercontent.com/assets/8723379/9523766/de7d9cc2-4cb1-11e5-9bfd-4f79e244b5c7.jpg)
