### ISSUE TITLE
Ambiente de trabalho

### ISSUE THREAD

**Issue by juniorlimajj** [EpicentroTec/epicentro#14]
# Sistema de arquivos:
- index.php;
- style.css;
- script.js;
- assets/
  - img/
  - fonts/
  - global/
    - global.css;
- modules/:
  - nomeDoModulo/
    - index.html;
    - style.css;
    - script.js;
  - ...

**Comment by juniorlimajj** [comment]
@joaosaragossa Favor verificar isso!!!

**Comment by joaosaragossa** [comment]
@josealbertorodriguesjunior Novo ambiente de trabalho em PHP disponível para teste e aprovação!

**Comment by joaosaragossa** [comment]
@josealbertorodriguesjunior Vamos trabalhar com uma indentação de 2 espaços, ok?

**Comment by juniorlimajj** [comment]
Tá Lindo!!!
