### ISSUE TITLE
JS do Módulo Menu

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#144]

**Comment by linsgabriel** [comment]
@jeehmilena 
Por favor, inserir os critérios de aceitação.

**Comment by jeehmilena** [comment]
# Critérios de Aceitação

@EpicentroTec/owners  Eu sendo usuário final:

**Versão desktop**
- Quero ver quando rolar o site o menu fixo no canto superior esquerdo 

**Versão mobile**
- Quero ver os tópicos do menu quando clicar
- Quero ver que quando o menu estiver selecionado tenha um efeito no menu de hambúrguer 
- Quero que quando clicar de volta o menu se fecha 

## Exemplos

**Versão Desktop**
![screenshot-livedemo00 template-help com 2015-08-26 20-12-31](https://cloud.githubusercontent.com/assets/8833388/9509032/aefd46ee-4c31-11e5-9b00-86bffd05e155.png)

**Versão Mobile**

![screenshot-www grandevillebuffet com br 2015-08-26 20-17-22](https://cloud.githubusercontent.com/assets/8833388/9509049/c670c5d0-4c31-11e5-8829-e17c7f080590.png)

**Comment by joaosaragossa** [comment]
@jeehmilena O Menu vai ter transparência quando rolar pra baixo? Se sim, de quanto?

**Comment by linsgabriel** [comment]
@joaosaragossa já começou fazer algo aqui?

**Comment by joaosaragossa** [comment]
@linsgabriel sim

**Comment by linsgabriel** [comment]
ok

**Comment by jeehmilena** [comment]
@joaosaragossa não vai ter transparência, já mandei o exemplo da imagem porque é pra ser seguido respeitando o logo e o conteudo do menu do epicentro.

**Comment by linsgabriel** [comment]
@jeehmilena vc disse que tinha gostado da transparência dos itens, apenas quando clicasse no hambúrguer. Ela seria mto mínima (95% ou `rgba(255,255,255,.95);`)

**Comment by jeehmilena** [comment]
@linsgabriel  a transparencia é pra vesão mobile quando clicasse, caso na clique não vai ter transparencia tanto pra versão desktop como pra versão mobile

**Comment by joaosaragossa** [comment]
@jeehmilena Revisa por favor e fecha a issue se tiver ok

**Comment by jeehmilena** [comment]
Está lindo!!!! Parabéns @joaosaragossa
