### ISSUE TITLE
JS do Módulo Jumbotron

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#145]

**Comment by linsgabriel** [comment]
@jeehmilena 
Por favor, inserir os critérios de aceitação.

**Comment by jeehmilena** [comment]
# Critérios de aceitação

Eu sendo usuário final:

**Versão Desktop**
- Quero ver um slider com X imagens com frases sendo carregadas automaticamente

**Versão Mobile**
- Quero ver a cada carregamento do site uma imagem com frase

**Comment by linsgabriel** [comment]
Eu não tenho certeza se consigo dentro desse curto prazo, pois não manjo tanto de js. 
Vou deixar essa issue livre e fazer separadamente. Se conseguir até lá eu implemento. 
@joaosaragossa vamos usar js puro, jquery ou os dois?

**Comment by joaosaragossa** [comment]
@linsgabriel Estou usando JQuery!

**Comment by joaosaragossa** [comment]
@linsgabriel @jeehmilena O Jumbotron está assim na versão mobile. É isso mesmo?

![screencapture-localhost-projects-epicentro-1441105949896](https://cloud.githubusercontent.com/assets/6151234/9602788/d2811330-5081-11e5-8ed7-98615558378b.png)

**Comment by jeehmilena** [comment]
@joaosaragossa  não porque na versão mobile não é slider

**Comment by joaosaragossa** [comment]
@jeehmilena Eu digo em relação a altura da tela, está 100%

**Comment by jeehmilena** [comment]
Em relação a altura tem que  se adaptando conforme a altura de cada dispositivo, no meu ta

**Comment by joaosaragossa** [comment]
@jeehmilena Então a altura do Jumbotron no mobile tem que ser a altura da tela, é isso?
