### ISSUE TITLE
JS do Módulo Portfolio

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#146]

**Comment by linsgabriel** [comment]
@jeehmilena 
Por favor, inserir os critérios de aceitação.

**Comment by jeehmilena** [comment]
# Critérios de aceitação

Eu sendo usuário final:

**Versão Desktop**
- Quero ver uma lista com X ícones clicáveis
- Quero ver quando clicar em um ícone que apareça automaticamente no notebook
- Quero ver no notebook uma barra de rolagem contendo a imagem inteira do site

**Comment by jeehmilena** [comment]
Vou fechar a issue porque o módulo está pronto! Parabéns @joaosaragossa  e @linsgabriel
