### ISSUE TITLE
JS do Módulo Contatos

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#147]

**Comment by linsgabriel** [comment]
@jeehmilena 
Por favor, inserir os critérios de aceitação.

**Comment by jeehmilena** [comment]
# Critérios de aceitação

Eu sendo usuário final quero ver

**Versão Desktop**
- Quero ver um formulário onde possa ser clicável a ponto de poder abri-lo e fecha-lo 
- Quero ver quando clicar no mapa que abra o mapa clicável em 1000px centralizado
- Quero ver quando aberto o mapa o formulário "minimizado" para que quando eu não quiser ver mais o mapa eu possa voltar para o modulo contato como no inicio do site

**Versão mobile**
- Quero ver um formulário onde possa ser clicável a ponto de poder abri-lo e fecha-lo  para que eu possa ter acesso ao mapa.
