### ISSUE TITLE
JS do Módulo Equipe

### ISSUE THREAD

**Issue by jeehmilena** [EpicentroTec/epicentro#149]
# Critérios de aceitação

Eu sendo usuário final 

**Versão desktop**
- Quero ver X fotos com X integrantes e quando passado o mouse apareça o nome e função
- Quero ver quando clicar que apareça em baixo o texto descritivo do integrante da equipe

**Versão Mobile**
- Quero ver X fotos com X integrantes e quando clicar apareça o nome e função

**Comment by joaosaragossa** [comment]
@jeehmilena Disponível pra revisão

**Comment by jeehmilena** [comment]
Fechando a issue módulo terminado :)
