### ISSUE TITLE
Sorteio de imagens do módulo jumbotron na versão responsiva

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#180]

**Comment by joaosaragossa** [comment]
Essa issue ficou a meu cargo, por isso me atribui ela.

**Comment by joaosaragossa** [comment]
Resolvi com javascript mesmo.

**Comment by joaosaragossa** [comment]
@EpicentroTec/owners Aqui o sorteio está funcionando. Por favor testem para fecharmos essa issue.

**Comment by jeehmilena** [comment]
No meu também está funcionando @joaosaragossa
