### ISSUE TITLE
Carregamento seletivo de imagens

### ISSUE THREAD

**Issue by aa779** [EpicentroTec/epicentro#185]
Usar mediaqueries testadas para carregamento seletivo das imagens nas resoluções: 320, 640, 800, 1024, 1280, 1440, 1920px nos módulos Jumbotron, Equipe e Frase.

Arquivos de teste disponibilizados para o João.

**Comment by joaosaragossa** [comment]
@EpicentroTec/owners Por favor testem, se estiver ok, fechamos essa issue.

**Comment by aa779** [comment]
@joaosaragossa , onde está aquela correção que você fez hoje? 
(321 carrega 640, 641 carrega 800 etc.)
