### ISSUE TITLE
Arquitetura da informação  

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#2]
Estabelecer parcialmente os conteúdos que serão expostos no site. Destacando cada módulo, os elementos que fazem parte e localização de ambos.

**Comment by linsgabriel** [comment]
[Arquitetura da informação](https://github.com/EpicentroTec/epicentro/wiki/Arquitetura-da-Informa%C3%A7%C3%A3o) escrita

**Comment by jeehmilena** [comment]
**Prévia**
![wireframe](https://cloud.githubusercontent.com/assets/8833388/8802227/7467d8c6-2f96-11e5-9940-1fa387f9e1f6.jpg)

**Comment by aa779** [comment]
@jeehmilena , a minha sugestão para o portfólio era que os ícones dos trabalhos ficassem dentro da tela do note. Pode ter setas dos lados e ser redondo. Mas testa dentro da tela, por favor.
