### ISSUE TITLE
Conteúdo - Módulo Jumbotron

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#3]
Criação das imagens (criar pasta no [drive](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg) e mandar link);
3 frases (uma de cada imagem);
Conforme design #9.

**Comment by joaosaragossa** [comment]
"A Epicentro Tecnologia desenvolve soluções em páginas web, sistemas de gerenciamento de conteúdo e design gráfico"

"Sites 100% responsivos, administração intuitiva com WordPress, integração com redes sociais e otimização para o Google Analytics"

"Produzimos seu projeto do design ao conteúdo, personalizado para as suas necessidades e focado na obtenção de resultados"

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final quero ver:
-  X fotos ocupando 100% da tela;
-  Quero ver uma camada sobrepondo a foto de cor: #3b0622 com 15% de opacidade;
-  Quero ver X frases centralizada na horizontal e vertical com a fonte da issue #9 ;
-  Quero ver  "telefone Ubatuba-SP", centralizado na horizontal e vertical embaixo da frase com a seguinte fonte #9

**Comment by joaosaragossa** [comment]
@jeehmilena vc tem que especificar a fonte usada nesse módulo, na issue #9 tem uma lista com várias

**Comment by jeehmilena** [comment]
![gabriel](https://cloud.githubusercontent.com/assets/8833388/9024111/92e32c1a-3892-11e5-9fd7-40d4cfdc23a7.jpg)

@EpicentroTec/owners  foto que vai ser usada para o Jumbotron :D
