### ISSUE TITLE
HTML Módulo Contato

### ISSUE THREAD

**Issue by joaosaragossa** [EpicentroTec/epicentro#39]
# Critérios de Aceitação
- Elemento de sessão com a classe `section contato` e um id `contato`
  - Um título de primeiro nível com a palavra "Contato"
  - Um formulário com a classe `form`
    - Um elemento `<label>` com a palavra "Nome" seguindo por um elemento de input do tipo texto
    - Um elemento `<label>` com a palavra "Email" seguindo por um elemento de input do tipo email
    - Um elemento `<label>` com a palavra "Mensagem" seguindo por um elemento `<textarea>`
    - Um elemento input do tipo submit com um atributo value "Enviar"
    - Um botão com uma classe `close`

**Comment by jeehmilena** [comment]
Falta o campo assunto @josealbertorodriguesjunior  e @joaosaragossa

**Comment by jeehmilena** [comment]
Já está tudo arrumado estou fechando a issue
