### ISSUE TITLE
Conteúdo - Módulo Serviços

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#4]
Imagens de cada serviço (criar pasta no [drive](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg) e mandar links);
Descrição de cada serviço;
Tudo conforme design #9.

**Comment by linsgabriel** [comment]
@EpicentroTec/owners 
Todos estão responsáveis

**Comment by joaosaragossa** [comment]
Mais uma vez recomento o uso de fonticons, como o [Font Awesome](http://fontawesome.io/icons/)

**Comment by linsgabriel** [comment]
Boa! Mais css, menos imagens!

**Comment by jeehmilena** [comment]
*\* CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final:
- Quero ver o titulo "SERVIÇOS", com a fonte #9 da cor preta;
- Quero ver uma fixa branca com 100%de largura e 100px de altura;
- Quero ver esse bloco com um fundo de curtiça(imagem) com opacidade de 75%;
- Quero ver X serviços em retângulos de 199 x 297 contendo o titulo do serviço e uma breve descrição do serviço com as fontes e cores  #9, todos centralizados na horizontal com espaçamentos entre eles de 120px. (a inclinação é algo que fiz a olho então vai ficar complicado colocar aqui)

-Quero ver esse bloco com a altura de  de 745px;

**Comment by joaosaragossa** [comment]
@jeehmilena mesma coisa dos outros critérios, precisa especificar a fonte
