### ISSUE TITLE
Conteúdo - Módulo Portfólio

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#5]
Imagem de fundo do notebook;
Imagens dos projetos (criar pasta no [drive](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg) e mandar link);
conforme design #9

**Comment by joaosaragossa** [comment]
Fiz upload de alguns exemplos [aqui](https://drive.google.com/drive/folders/0B0luQkerNSInfmRTejZqTUhqeXUyc0ZoUEJ3M0RMdlYzVXR0S292U0VVS0t6d2ZZdHppZDA)

**Comment by joaosaragossa** [comment]
@linsgabriel Vai ter a descrição dos projetos? Se não, edita seu comentário por favor

**Comment by linsgabriel** [comment]
Editado!

**Comment by jeehmilena** [comment]
vou fazer os critérios de aceitação hj @aa779  @joaosaragossa  @linsgabriel  e @josealbertorodriguesjunior  se preparem :smiling_imp:

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final :
- Quero ver o titulo "PORTIFÓLIO", com a fonte #9 da cor branca;
- Quero ver uma faixa de cor: #8a2f30 com 100% de largura e 100px de altura;
- Quero ver este bloco com o fundo branco e o desenho do logo do Epicentro no fundo alinhado a direita com 1000x1000 de tamanho
- Quero ver a imagem de um notebook com 1289x660 de tamanho, contendo a imagem de X sites
- Quero ver dentro do notebook um menu no top contendo X opções de sites 
- Quero ver este bloco com a altura de 1142px
