### ISSUE TITLE
CSS Módulo Menu

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#50]
- Um bloco retangular com 918 x 85 de cor branca, centralizado e fixo no topo;
- Logo alinhado a esquerda;
- Itens "SERVIÇOS, PORTFÓLIO, EQUIPE, CONTATOS" alinhados a direita com a fonte #9 e cor #842c2e.

**Comment by jeehmilena** [comment]
https://drive.google.com/drive/u/0/folders/0B-83OL8jrsCOfmhXS2ZacVpvWVYtU2tnV0VBa2tqZmtRNGZtM01FMGMxQnFFLVBZWjh3Zlk
 link logo

**Comment by linsgabriel** [comment]
Thankss

**Comment by jeehmilena** [comment]
@linsgabriel  na resolução para celular o meu de hamburguer não está alinhado ao logo do epicentro

**Comment by jeehmilena** [comment]
@linsgabriel  revisa o tamanho do logo ele ta "achatado" ta bem pouco mais ta

![screenshot-localhost 2015-08-04 16-07-57](https://cloud.githubusercontent.com/assets/8833388/9069981/21a16ea8-3ac3-11e5-9e39-defbb643e453.png)

**Comment by joaosaragossa** [comment]
@linsgabriel Você vai conseguir resolver isso se deixar o valor do `width` da imagem para `auto`
