### ISSUE TITLE
CSS Módulo Jumbotron

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#51]
- 3 fotos ocupando 100% da tela;
- Camada sobrepondo a foto de cor: #3b0622 com 15% de opacidade;
- Frase de cada foto centralizada na horizontal e vertical com a fonte da issue #9 ;
- "telefone Ubatuba-SP", centralizado horizontalmente e na base da foto, embaixo da frase com a seguinte fonte #9

**Comment by joaosaragossa** [comment]
@jeehmilena Por favor, escolha as três fotos que vão estar no Jumbotron, coloque no drive e link aqui

**Comment by jeehmilena** [comment]
As fotos ja estão escolhidas e no drive. Só usar @EpicentroTec/owners 
https://drive.google.com/drive/u/0/folders/0B-83OL8jrsCOfi1sY0F5SVVSazJvZDliZTdub3ZoWmNfd3g2aW4tZ3JJR3J5R2lSNHFLanM

**Comment by jeehmilena** [comment]
**Correções serem feitas no Jumbotron** 
- A partir de 800 para baixo quando clicar no menu e sobrepor a imagem, esconder a frase. 
- Fonte do "Telefone-Ubatuba SP" não está conforme o design 
- Jumbotron não está ocupando 100% ta tela na resolução de 1920 
- Obs: esqueci de dizer que na frase exite um espaçamento entre fontes de 5px 
- Número do telefone: 3832-6789

**Comment by joaosaragossa** [comment]
@jeehmilena me explica melhor o que seria espaçamento entre fontes

**Comment by joaosaragossa** [comment]
@jeehmilena Revisa esse PR. Ficou faltando só esse primeiro ponto que precisamos conversar melhor e esse lance do espaçamento que não entendi.

**Comment by joaosaragossa** [comment]
@jeehmilena Se estiver tudo certo, fecha essa issue

**Comment by jeehmilena** [comment]
espaçamento entre cada letra da frase, é isso

**Comment by joaosaragossa** [comment]
@jeehmilena Ficou assim, é isso mesmo?
![captura de tela de 2015-08-05 15 32 13](https://cloud.githubusercontent.com/assets/6151234/9095360/42b1db80-3b8d-11e5-8bfc-c80fbe92fd63.png)

**Comment by jeehmilena** [comment]
@joaosaragossa  um pouco mais junta talvez um espaçamento de 4px fique legal, no mais ta perfeito

**Comment by joaosaragossa** [comment]
@jeehmilena Prono. Se tiver tudo certo pode fechar essa issue

**Comment by jeehmilena** [comment]
https://drive.google.com/drive/u/0/folders/0B-83OL8jrsCOfi1sY0F5SVVSazJvZDliZTdub3ZoWmNfd3g2aW4tZ3JJR3J5R2lSNHFLanM 

2º imagem pro jumbotron

**Comment by linsgabriel** [comment]
@EpicentroTec/owners 
Estabelecer as 3 imagens e qual frase de cada imagem!

**Comment by jeehmilena** [comment]
As 3 imagens já estão na pasta assets/img e criei uma issue pra a criação das frases, sendo assim estou fechando essa issue
