### ISSUE TITLE
CSS Módulo Serviços

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#52]
- Titulo "SERVIÇOS", com a fonte #9 da cor preta;
- Faixa branca com 100% de largura e 100px de altura;
- Bloco com um fundo de curtiça (imagem) com opacidade de 75%;
- Os 5 serviços em retângulos de 199 x 297 contendo o ícone, o titulo e uma breve descrição do serviço, com as fontes e cores #9, todos centralizados na vertical com espaçamentos entre eles de 120px e levemente inclinados;
- Bloco com a altura de de 745px;

**Comment by joaosaragossa** [comment]
Vou fazer essa ninguém toca

**Comment by jeehmilena** [comment]
kkkkkkkkkkkkk :+1:

**Comment by jeehmilena** [comment]
https://drive.google.com/drive/u/0/folders/0B-83OL8jrsCOfjlsd1JENXIzZXpROHRvdE1RNmdIRy1QY3ZzRVZ3X3ZyVllrVWJHUGUxNFk link imagens

**Comment by joaosaragossa** [comment]
@jeehmilena Da uma olhada, eu troquei o fundo por uma imagem vetorizada, acho que ficou bem melhor.

**Comment by jeehmilena** [comment]
@joaosaragossa  achei  bacana a imagem testa com a opacidade que ta nos critérios de aceitação e com a cor das tarraxas que te falei!

**Comment by joaosaragossa** [comment]
@jeehmilena Eu testei com opacidade mas achei que ficou muito claro, as cores dos postits ficaram ofuscadas pela claridade do fundo, amanhã eu te mostro.
Sobre as tarraxas acho que tem que manter essa cor, pois é a cor da tarraxas (nunca vi tarraxas pretas). Com outra cor não sei se o usuário vai identificar.

**Comment by jeehmilena** [comment]
Reabri  a issue porque testei o modulo com uma textura diferente e acho que ficou melhor

**Comment by joaosaragossa** [comment]
@jeehmilena O problema desse fundo é que está com a marca d'agua, não dá pra ir pro ar assim

**Comment by joaosaragossa** [comment]
@jeehmilena Você não consegue um fundo semelhante sem a marca?

**Comment by jeehmilena** [comment]
pouts que droga, pior que eu gostei da cor, vou ver se acho

**Comment by jeehmilena** [comment]
@joaosaragossa  e se cortar a imagem :D

**Comment by joaosaragossa** [comment]
@jeehmilena testa ai, mas eu acho que vai dar pra ver que ta sendo repetido, tipo o fundo o site do álvaro

**Comment by jeehmilena** [comment]
kkkkkkkk ai é foda

**Comment by joaosaragossa** [comment]
@jeehmilena outra alternativa é tratar o fundo que eu coloquei pra ficar na cor que vc quer

**Comment by jeehmilena** [comment]
@joaosaragossa  o que vc acha de uma cortiça de cor diferente? tipo cinza?

**Comment by joaosaragossa** [comment]
@jeehmilena Nunca vi cortiça de outra cor, mas se você encontrar... ou deixa ela preto-e-branco no photoshop

**Comment by jeehmilena** [comment]
@joaosaragossa  tirei a marca d'agua kkk ve se tabom 

![curtica](https://cloud.githubusercontent.com/assets/8833388/9069771/a180231e-3ac1-11e5-89f5-1dc787095ec3.jpg)

**Comment by joaosaragossa** [comment]
@jeehmilena Legal! Testa ai pra ver se ela não repete

**Comment by joaosaragossa** [comment]
@jeehmilena Se estiver tudo certo, fecha essa issue pfvr

**Comment by jeehmilena** [comment]
@aa779  se puder faz os textos dos serviços : )

**Comment by jeehmilena** [comment]
Só falta o conteúdo de cada serviço @aa779  pode fazer isso?

**Comment by jeehmilena** [comment]
Modulo serviços só esperando as correções do @joaosaragossa e depois será fechada

**Comment by linsgabriel** [comment]
@joaosaragossa  
O percevejo está se repetindo dentro do postit.. 
Por favor, mande suas alterações novamente.. Obg.

**Comment by joaosaragossa** [comment]
@jeehmilena Mandei um PR diminuindo o tamanho dos ícones dos postits pra caber o texto dentro, por me diga se é suficiente
