### ISSUE TITLE
CSS Módulo Portfólio

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#53]
- Titulo "PORTFÓLIO", com a fonte #9 da cor branca;
- Faixa de cor `#8a2f30` com 100% de largura e 100px de altura;
- Bloco com o fundo branco e o desenho do logo do Epicentro no fundo alinhado a direita com 1000x1000 de tamanho;
- Imagem de um notebook com 1289x660 de tamanho, contendo a imagem de x sites;
- Dentro do notebook um menu no topo contendo X links de sites;
- Bloco com a altura de 1142px

**Comment by jeehmilena** [comment]
https://drive.google.com/drive/u/0/folders/0B0luQkerNSInfmRTejZqTUhqeXUyc0ZoUEJ3M0RMdlYzVXR0S292U0VVS0t6d2ZZdHppZDA
link imagens

**Comment by jeehmilena** [comment]
@linsgabriel  as setinhas :) 

https://drive.google.com/drive/u/0/folders/0B0luQkerNSInfmRTejZqTUhqeXUyc0ZoUEJ3M0RMdlYzVXR0S292U0VVS0t6d2ZZdHppZDA

**Comment by linsgabriel** [comment]
@EpicentroTec/owners 
Se forem colocar mais projetos, vamos relacionar os projetos e screenshots e ícones!
Lembrando que isso é uma mudança estrutural;
Caso for adicionar eu altero no css;

**Comment by jeehmilena** [comment]
Esperando as correções do @linsgabriel  para fechar essa issue, lembrando que existe um issue para os Screenshots do modulo projetos

**Comment by linsgabriel** [comment]
@jeehmilena  Posso fechar?

**Comment by jeehmilena** [comment]
Calma tem que ver a questão da setinha : )

**Comment by linsgabriel** [comment]
Amanhã fazemos isso na sua resolução, ok? 
9:00 hrs
