### ISSUE TITLE
CSS Módulo Frase

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#54]
- Fundo transparente mostrando o fundo do `body`;
- Foto de fundo do `body` que ocupe 100% da tela;
- Quero o conteúdo centralizado em 1000px de largura;
- Faixa branca com 100% de largura e 280px de altura;
- Frase centralizada na horizontal e vertical com a cor `#520034` e a fonte #9.

**Comment by linsgabriel** [comment]
- Fundo transparente mostrando o fundo do `body`;
- Foto de fundo que ocupe 100% da tela;
- Quero o conteúdo centralizado em 1000px de largura;
- Faixa branca com 100% de largura e 280px de altura;
- Frase centralizada na horizontal e vertical com a cor #520034 e a fonte #9.

**Comment by joaosaragossa** [comment]
@linsgabriel @jeehmilena Vou fazer essa, preciso saber qual imagem de fundo vamos usar. Levando em consideração a frase - "A Epicentro conta com profissionais especializados e sintonizados com as tendencias do mercado de desenvolvimento web" - acho que cairiam bem [essa](https://drive.google.com/open?id=0B0luQkerNSInVUMyUFotUkpNZzA) ou [essa](https://drive.google.com/open?id=0B0luQkerNSInRktVRWJsVy1nN2s) foto da equipe

**Comment by jeehmilena** [comment]
Acho legal não usarmos uma foto nossa 1º pq o @linsgabriel  ta de chinelo --'
2º da a intender que somos muito "narcisista", acho legal usarmos uma imagem aleatória 
tipo essa 

![36946 53034-controlar-o-computador-pelo-celular](https://cloud.githubusercontent.com/assets/8833388/9069860/483a4f90-3ac2-11e5-8554-35b1169d4fac.jpg)

**Comment by joaosaragossa** [comment]
@jeehmilena verdade, talvez essa fiquem bem no fundo do modulo equipe... mas escolhe uma ai então pra eu começar

**Comment by jeehmilena** [comment]
hummm põe essa pra teste enquanto eu procura uma aqui pra eu te mandar

**Comment by joaosaragossa** [comment]
@jeehmilena Ok!

**Comment by joaosaragossa** [comment]
@jeehmilena Disponível pra revisão

**Comment by jeehmilena** [comment]
**Observações e correções**
- Pode deixar a cor da faixa sólida
- Pode deixar a faixa com o padding de 3em
- Deixar a faixa centralizada na vertical e horizontal na imagem
- Não esquecer do movimento que vai ter igual a do site http://arquiteturadeinformacao.com/blogs-livros-links-cursos-eventos-de-arquitetura-de-informacao/
- No responsivo para celular  não vai ter o modulo "frase"
  @joaosaragossa  @linsgabriel

**Comment by joaosaragossa** [comment]
@jeehmilena Disponível para revisão.
Obs: A animação vai ser feita no milestone de Comportamento

**Comment by joaosaragossa** [comment]
@jeehmilena Ficou assim, é isso mesmo?
![captura de tela de 2015-08-05 15 32 13](https://cloud.githubusercontent.com/assets/6151234/9094283/4229d506-3b87-11e5-924a-5c76dde8927a.png)

**Comment by joaosaragossa** [comment]
@jeehmilena Se tiver tudo certo, feche essa issue pfvr

**Comment by jeehmilena** [comment]
Fechando o modulo frase :)
