### ISSUE TITLE
CSS Módulo Equipe

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#55]
- Titulo "EQUIPE", com a fonte #9 da cor branca;
- Conteúdo centralizado em 1000px de largura;
- Faixa da cor `#3a0026` com 100% de largura e 100px de altura;
- 5 fotos de membros da equipe com 155x155 de tamanho;
- Ao passar o mouse, a foto aumenta para 207x207, com transparência de cor `#53193f` com opacidade de 40%, com o nome e função na fonte #9;
- Uma imagem de fundo do bloco com uma sobreposição com a cor `#40002a` e opacidade de 90%;
- Bloco com altura de 810px.

**Comment by jeehmilena** [comment]
usa essa por enquanto 

![acesse-bahia-e-equipe1](https://cloud.githubusercontent.com/assets/8833388/9171967/3fbf3ce4-3f46-11e5-88f6-1c671d8fe8af.jpg)

@linsgabriel

**Comment by jeehmilena** [comment]
Nova foto da equipe reunida kkkkkkkkkkkkkkkkkkkkkkkkk @linsgabriel , @aa779  @josealbertorodriguesjunior , @joaosaragossa 

![dsc04956](https://cloud.githubusercontent.com/assets/8833388/9173730/5a9d78c6-3f52-11e5-827b-ffa9a253db57.jpg)

**Comment by linsgabriel** [comment]
@aa779 Por favor, mandar as fotos aqui ou link (caso tenha armazenado em outro lugar).
Não precisa fazer Push, apenas anexar!

**Comment by linsgabriel** [comment]
Eu vou trocar as fotos!

**Comment by jeehmilena** [comment]
Para fechar o modulo equipe deve ter os textos de cada integrante no html do site, os textos do @aa779 , @joaosaragossa  e @josealbertorodriguesjunior  ja estão no drive

**Comment by linsgabriel** [comment]
@EpicentroTec/owners 
Escrevam seus textos em um arquivo compartilhado por todos.
Breve e objetivo, sobre sua função no Epicentro e a Web (ou sendo mais amplo, ex: TI) na sua vida!

**Comment by linsgabriel** [comment]
@jeehmilena 
Espero a aprovação do visual desse módulo, para fechar a issue!
