### ISSUE TITLE
CSS Módulo Contatos

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#56]
- Titulo "CONTATOS", com a fonte #9 da cor `#8a2f31`;
- Conteúdo centralizado em 1000px de largura;
- Faixa branca com 100% de largura e 100px de altura;
- Mapa no fundo do bloco com uma sobreposição de cor branca com opacidade de 50%;
- Formulário de 315 x 425 de cor preta com opacidade de 30%;
- Campos: `nome`, `email`, `assunto` e `mensagem` com a fonte #9 de cor preta;
- Botão Enviar de cor #8a2f31 com 125x30 alinhado a esquerda do formulário;
- Bloco com 700px de altura;

**Comment by linsgabriel** [comment]
- Título com a cor `#8a2f31`;
- Conteúdo centralizado em 1000px de largura;
- Faixa branca com 100% de largura e 100px de altura;
- Mapa no fundo desse bloco com uma sobreposição de cor branca com opacidade de 50%;
- Formulário de 315 x 425 de cor preta com opacidade de 30%;
- Campos do form: nome, email, assunto e mensagem com a fonte #9 de cor preta;
Botão Enviar da cor #8a2f31 com 125 x 30 alinhado a esquerda do formulário
Bloco com 700px de altura.

**Comment by joaosaragossa** [comment]
@jeehmilena Disponível pra revisão

**Comment by linsgabriel** [comment]
@joaosaragossa, nessa issue deve ser feito uma alteração, segundo a designer do projeto @jeehmilena:
- alinhar campos `nome` e  `email` à esquerda;

**Comment by joaosaragossa** [comment]
@jeehmilena da uma olhada nesse PR, alterei a opacidade das camadas como vc tinha dito, se tiver ok pode fazer merge

**Comment by linsgabriel** [comment]
Como está esse módulo?
@jeehmilena Aceitou visualmente?
Se sim, pode ser fechada essa issue!
