### ISSUE TITLE
CSS Módulo Footer

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#57]
- Conteúdo centralizado em 1000px de largura
- "REDES SOCIAIS" com a fonte #9 de cor preta, e os respectivos Ícones de cada rede social com tamanho de 41x41;
- Telefone e email com a fonte #9 de cor preta;
- Logomarca com 330x80;
- Copyright com a fonte #9;
- Bloco com a cor de fundo #e9e9ec e altura de 250px;

**Comment by joaosaragossa** [comment]
Vou fazer essa

**Comment by joaosaragossa** [comment]
@jeehmilena Disponível para revisão

**Comment by linsgabriel** [comment]
@joaosaragossa 
Segundo a designer @jeehmilena, uma alteração precisa ser feita:
- centralizar os ícones de redes sociais, abaixo do título "REDES SOCIAIS"
