### ISSUE TITLE
CSS Responsividade

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#58]
Para que façamos o milestone de Apresentação da maneira correta e poupando nosso tempo, devemos fazer as adaptações necessárias para todas resoluções. Então é necessário: 
- Escolher quais resoluções vamos adotar nas `@media`;
- Possíveis mudanças no comportamento de determinado módulo ou elemento em determinada resolução;
- Diminuir algum conteúdo?
- Vamos pensar nisso de acordo com o Design #9.

**Comment by linsgabriel** [comment]
Minha sugestão:
320 - 600
601 - 800
801 - 1024
1025 ...

**Comment by linsgabriel** [comment]
@EpicentroTec/owners

**Comment by linsgabriel** [comment]
Não é mobile first!
Fazemos para desktop `>1024px`;
Posteriormente adaptamos para as outras resoluções, de uma forma decrescente:
- `código normal { ... }` - Aqui fica de 1025px adiante. (desktop)
- `@media screen and (max-width: 1024px) { ... }` - Entre 801 e 1024px. (tablet horizontal)
- `@media screen and (max-width: 800px) { ... }` - Entre 601 e 800px. (tablet vertical)
- `@media screen and (max-width: 600px) { ... }` - Entre 320 e 600px. (smartphones)

**Comment by joaosaragossa** [comment]
@linsgabriel Só agora que vi seu comentário, por isso que comecei a fazer mobile first! :P

**Comment by linsgabriel** [comment]
tranquilo kkk
