### ISSUE TITLE
Conteúdo - Módulo Equipe

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#6]
Imagens dos membros da equipe (criar pasta no drive e mandar [link](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg));
Nome, função e breve descrição de cada membro;
conforme design #9.

**Comment by joaosaragossa** [comment]
Criei a pasta para imagens de membros da equipe [aqui](https://drive.google.com/drive/folders/0B0luQkerNSInfl9Eb1hWSENZMWlycEFYa3FfdDA4OHlWV3JNRGthdEtOakdBZWtXWF9yV0U) e fiz upload da minha

**Comment by joaosaragossa** [comment]
@EpicentroTec/owners Façam upload das suas fotos

**Comment by jeehmilena** [comment]
Obs: fotos decentes :)

**Comment by joaosaragossa** [comment]
Sem nudez kkk

**Comment by jeehmilena** [comment]
kkkkkkkkkkkk isso mesmo  @joaosaragossa  sem nudez leu bem né @linsgabriel  e @aa779  kkkkkkkkkkkkkkkkkkkkk

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final:
- Quero ver o titulo "EQUIPE", com a fonte #9 da cor branca;
- Quero o conteúdo centralizado em 1000px de largura
- Quero ver uma faixa da cor #3a0026 com 100% de largura e 100px de altura
- Quero ver X fotos de membros da equipe com 155 x 155
- Quero ver quando passar o mouse que a foto aumente para 207 x 207, com uma transparencia de cor #53193f com opacidade de 40%, com o nome e função com a fonte #9 
- Quero ver no fundo desse bloco uma imagem que ocupe o tamanho do bloco com uma sobreposição com a cor #40002a e opacidade de 90%
- Quero ver esse bloco com altura de 810px;

**Comment by joaosaragossa** [comment]
Ainda faltam as fotos do @linsgabriel e do @aa779 ! Por favor façam o upload pra fechar essa issue.

**Comment by aa779** [comment]
![alvaro](https://cloud.githubusercontent.com/assets/8723379/9175580/cba8eeba-3f5c-11e5-8b07-7904c938aaf4.jpg)
![gabriel][(https://cloud.githubusercontent.com/assets/8833388/9182429/0619ada4-3f81-11e5-8851-d7c7273d3282.jpg)
![joao](https://cloud.githubusercontent.com/assets/8723379/9175582/cbcf3566-3f5c-11e5-8c1c-c8d13231b817.jpg)

**Comment by aa779** [comment]
![gabriel](https://cloud.githubusercontent.com/assets/8723379/9175656/3e5449fa-3f5d-11e5-9167-d2b206aab17b.jpg)
