### ISSUE TITLE
Conteúdo - Módulo Contatos

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#7]
Imagem provisória para mapa (criar pasta no [drive](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg) e mandar link); 
Conforme design #9.

**Comment by joaosaragossa** [comment]
Tirei alguns prints, está [nesta](https://drive.google.com/drive/folders/0B-83OL8jrsCOfjVQT0RFOE9mNWRzVjNtR1JYR3BaeUYwQ21lYUN4LXhXRmZtcjQtdm5ja0E) pasta.

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final :
- Quero ver o titulo "CONTATO", com a fonte #9 da cor #8a2f31;
- Quero o conteúdo centralizado em 1000px de largura
- Quero ver uma faixa branca com 100%de largura e 100px de altura
- Quero ver um mapa no fundo desse bloco com uma sobreposição de cor branca com opacidade de 50%
- Quero ver um formulário de 315 x 425 de cor preta com opacidade de 30% contendo os seguintes campos: nome, email, assunto e mensagem com a fonte  #9 de cor preta, com um botão da cor #8a2f31 com 125 x 30 alinhado a esquerda do formulário
- Quero ver esse bloco com 700px de altura
