### ISSUE TITLE
Tarraxas Módulo Serviços

### ISSUE THREAD

**Issue by joaosaragossa** [EpicentroTec/epicentro#79]

**Comment by joaosaragossa** [comment]
@jeehmilena O que acha?
![captura de tela de 2015-08-04 14 58 39](https://cloud.githubusercontent.com/assets/6151234/9068354/69f9eff4-3ab9-11e5-825a-0b4aabf4d9d3.png)

**Comment by jeehmilena** [comment]
Acho que ficou muito falso @joaosaragossa , melhor deixar como tava antes kkkkkk

**Comment by joaosaragossa** [comment]
@jeehmilena melhor mesmo
