### ISSUE TITLE
Conteúdo - Módulo footer

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#8]
Imagens dos ícones do facebook e GitHub (criar pasta no [drive](https://drive.google.com/drive/folders/0B4FpUQisHeUlfmMyRmFVVldqRGg0Z3loQW5qOGljdUtsNTlqSDVHSDhsWFFId1R4NjRvdTg) e mandar link);
Conforme design #9.

**Comment by joaosaragossa** [comment]
Sou a favor de usar uma fonticon, como o [Font Awesome](http://fontawesome.io/)

**Comment by jeehmilena** [comment]
**CRITÉRIOS DE ACEITAÇÃO**

Eu sendo usuário final :
- Quero o conteúdo centralizado em 1000px de largura
- Quero ver as redes socias com a fonte #9 de cor preta, e os respectivos icones de cada rede social com tamanho de 41 x 41
- Quero ver telefone e email com a fonte #9 de cor preta 
- Quero ver a logomarca com 330 x 80
- Quero ver o copyright com a fonte #9 
- Quero ver esse bloco com a cor de fundo #e9e9ec e altura de 250px;
