### ISSUE TITLE
Design 1.0

### ISSUE THREAD

**Issue by linsgabriel** [EpicentroTec/epicentro#9]

**Comment by jeehmilena** [comment]
**FONTES**

_**Jumbotron**_ 
_Menu_ : Alegreya Sans SC, 20px;
_Frase_ : Alegreya Sans, 30px;
_Telefone e cidade_ : Alegreya Sans, 18px;

_**Titulos (serviços,portifólio,equipe e contato)**_ 
Alegreya Sans SC, 50px;

_**Subtitulos(serviços)**_
_Subtitulo_ : Alegreya Sans, 20px;
_Texto descritivo_ : Rosario italic, 12px;

_**Frase**_
Alegreya Sans SC, 50px;

_**Nome e função(equipe)**_
_Subtitulo_ :  Alegreya Sans, 20px;
_Texto_  : Alegreya Sans, 15px;

_**Formulario**_
_Campos_: Alegreya Sans SC, 15px;
_Botao "ENVIAR": Alegreya Sans SC, 20px;

_**Rodapé**_
_Titulos(redes sociais, telefone e email)_ : Alegreya Sans SC, 18px;
_Email_ : Arial, 15px;
_Copyright_ : Raleway, 13px;

**CORES**

![cores](https://cloud.githubusercontent.com/assets/8833388/8837275/f303ed72-309b-11e5-8615-b659607fc863.jpg)

**VERSÃO DESKTOP**

![sem titulo-1](https://cloud.githubusercontent.com/assets/8833388/8958920/1a8f9502-35de-11e5-9b76-a5677fa3fe7b.jpg)

**VERSÃO MOBILE (sugestão)**

![versao-mobile](https://cloud.githubusercontent.com/assets/8833388/8937843/691148e0-3531-11e5-9fe4-12b33dfd9c95.jpg)

@joaosaragossa , @aa779 , @josealbertorodriguesjunior , @linsgabriel

**Comment by joaosaragossa** [comment]
Show!

**Comment by aa779** [comment]
@jeehmilena , parabéns pelo trabalho! Estamos orgulhosos!

Publica o wireframe aqui também, por favor!

**Comment by jeehmilena** [comment]
Muito obrigada @aa779 , apenas quero que tudo que estamos planejando para o Epicentro de certo!!!
